services:
  elasticsearch:
    image: elasticsearch:8.17.1
    ports:
    - "9200:9200"
    - "9300:9300"
    deploy:
      resources:
        limits:
          memory: 1G
    networks: [elastic]
    environment:
    - discovery.type=single-node
    - xpack.security.enabled=false
    volumes:
    - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  nutch:
    image: apache/nutch:latest
    platform: linux/amd64
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks: [elastic]
    volumes:
    - ./seeds.txt:/opt/nutch/seeds.txt
    - ./nutch-site.xml:/opt/nutch/conf/nutch-site.xml
    command: [
      "crawl",
      "-i",
      "-D", "elastic.index=nutch_index",
      "-s", "/opt/nutch/seeds.txt",
      "crawl", "3"
    ]

  kibana:
    image: kibana:8.17.1
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
    - "5601:5601"
    environment:
    - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    - SERVER_NAME=kibana
    networks: [elastic]

networks:
  elastic:

volumes:
  esdata:
