services:
  elasticsearch:
    image: elasticsearch:8.17.1
    ports:
    - 9200
    deploy:
      resources:
        limits:
          memory: 1G
    networks: [elastic]
    environment:
    - discovery.type=single-node
    - xpack.security.enabled=false
    volumes:
    - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  crawler:
    image: docker.elastic.co/integrations/crawler:0.2.0
    command: -c "bin/crawler crawl config/parks.yaml"
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
    - ./parks.yaml:/app/config/parks.yaml
    networks:
    - elastic

  kibana:
    image: kibana:8.17.1
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
    - 5601
    environment:
    - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    - SERVER_NAME=kibana
    networks: [elastic]

  web-server:
    build: .
    environment:
    - LISTEN_PORT=8080
    - ELASTICSEARCH_ADDRESS=http://elasticsearch:9200
    ports:
    - "${PORT:-8080}:8080"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks: [elastic]

networks:
  elastic:

volumes:
  esdata:
