[package]
name = "search-api-elasticsearch"
version = "0.1.0"
edition = "2021"

[dependencies]
elasticsearch = "8.17.0-alpha.1"
serde = "1"
serde_json = "1"
async-trait = "0.1"
search-api = { path = "../search-api" }
